In [28]:
# import neccessary library
import datetime as dt 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress
import seaborn as sns
import os

In [29]:
# get the data from data folder
def index_data_loading(start_date, end_date, rebal_period):
    current_path = os.getcwd()
    print(current_path)
    base_dir = os.path.join('/Users', 'raymondli', 'Desktop', 'Machine Learning', 'Machine learning project')
    index_data_dir = os.path.join(base_dir, 'data', 'index_data')

    result_df = pd.DataFrame()
    
    index_data_name_file = {
        'msci_acwi':'MSCI_All Country World.xlsx',
        'msci_world':'MSCI World.xlsx',
        'msci_emerging':'MSCI Emerging.xlsx',
        'msci_world_gross':'MSCI World Gross.xlsx',
        'msci_world_value':'MSCI World Value.xlsx',
        'msci_real_estate':'MSCI World Real Estate.xlsx',
        'bb_world_agg':'Bloomberg Barclays US AGG.xlsx',
        'bb_emerging_agg':'Bloomberg Barclays EM AGG.xlsx',
        'bb_corp_ig':'Bloomberg Barclays US Corp IG.xlsx',
        'bb_corp_hy':'Bloomberg Barclays US Corp HY.xlsx',
        'bb_infla_protect':'Bloomberg Barclays US Inflation Protected 7-10 year.xlsx',
        'snp_commodity':'SNP GSCI TR.xlsx',
        'us_short_treasury':'Bloomberg Barclays US 1-3 month treasury.xlsx',
    }
    
    for ind_name in index_data_name_file.keys():
        #load_index_data(self.start_date, self.end_date, index_data_dir, index_data_name_file[ind_name], ind_name)
        input = pd.read_excel(os.path.join(index_data_dir, index_data_name_file[ind_name]), index_col='Date')
        input = input.sort_index(ascending=False)
        #calculate percentage change on month level
        index_df = input.iloc[:, 0].resample(rebal_period).first().pct_change().fillna(0)
        index_df.rename(ind_name, inplace=True)
        index_df = index_df.loc[start_date:end_date]
        result_df = pd.concat([result_df, index_df], axis=1).fillna(0)
        
    
    result_df.index = pd.to_datetime(result_df.index)
    return result_df

def index_cum_data_loading(start_date, end_date, rebal_period):
    current_path = os.getcwd()
    print(current_path)
    base_dir = os.path.join('/Users', 'raymondli', 'Desktop', 'Machine Learning', 'Machine learning project')
    index_data_dir = os.path.join(base_dir, 'data', 'index_data')
    
    result_df = pd.DataFrame()
    
    index_data_name_file = {
        'msci_acwi':'MSCI_All Country World.xlsx',
        'msci_world':'MSCI World.xlsx',
        'msci_emerging':'MSCI Emerging.xlsx',
        'msci_world_gross':'MSCI World Gross.xlsx',
        'msci_world_value':'MSCI World Value.xlsx',
        'msci_real_estate':'MSCI World Real Estate.xlsx',
        'bb_world_agg':'Bloomberg Barclays US AGG.xlsx',
        'bb_emerging_agg':'Bloomberg Barclays EM AGG.xlsx',
        'bb_corp_ig':'Bloomberg Barclays US Corp IG.xlsx',
        'bb_corp_hy':'Bloomberg Barclays US Corp HY.xlsx',
        'bb_infla_protect':'Bloomberg Barclays US Inflation Protected 7-10 year.xlsx',
        'snp_commodity':'SNP GSCI TR.xlsx',
        'us_short_treasury':'Bloomberg Barclays US 1-3 month treasury.xlsx',
    }
    
    for ind_name in index_data_name_file.keys():
        #load_index_data(self.start_date, self.end_date, index_data_dir, index_data_name_file[ind_name], ind_name)
        input = pd.read_excel(os.path.join(index_data_dir, index_data_name_file[ind_name]), index_col='Date')
        input = input.sort_index(ascending=False)
        reb_index = input.iloc[:, 0].resample(rebal_period).first()
        #calculate percentage change on month level
        index_df = reb_index / reb_index.iloc[0]
        index_df = index_df.fillna(1)
        index_df.rename(ind_name, inplace=True)
        index_df = index_df.loc[start_date:end_date]
        result_df = pd.concat([result_df, index_df], axis=1).fillna(0)
        
    result_df.index = pd.to_datetime(result_df.index)
    return result_df

In [30]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
start_date = '1992-01-01'
end_date = '2021-06-30'
rebal_period = '1M'
data = index_data_loading(start_date, end_date, rebal_period)
data

/Users/raymondli/Desktop/Machine Learning/Machine learning project

,msci_acwi,msci_world,msci_emerging,msci_world_gross,msci_world_value,msci_real_estate,bb_world_agg,bb_emerging_agg,bb_corp_ig,bb_corp_hy,bb_infla_protect,snp_commodity,us_short_treasury
1992-01-31,0.000000,0.000000,0.000000,-0.031464,-0.009100,0.000000,-0.002171,0.000000,-0.002588,0.035225,0.000000,0.005368,-0.000984
1992-02-29,-0.017548,-0.020678,0.103012,-0.023750,-0.014170,0.000000,-0.013095,0.000000,-0.012103,0.024673,0.000000,0.025628,0.003087
1992-03-31,-0.015102,-0.017357,0.054748,-0.048605,-0.049508,0.000000,0.003074,0.000000,0.006558,0.012399,0.000000,-0.023659,-0.000196
1992-04-30,-0.063123,-0.066034,0.029763,-0.011712,0.035704,0.000000,0.003851,0.000000,0.005622,0.003798,0.000000,0.030560,0.009191
1992-05-31,0.026335,0.027579,-0.009451,0.042249,0.033392,0.000000,0.006528,0.000000,0.004180,0.014110,0.000000,0.023145,0.009302
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-28,0.009655,0.002914,0.053679,0.009748,-0.003860,0.008924,-0.006128,-0.007934,-0.010356,0.004106,0.004246,0.068418,0.000204
2021-03-31,0.027554,0.031810,0.001014,0.007317,0.056323,0.007271,-0.016604,-0.013898,-0.020684,0.005491,-0.020821,0.079945,-0.000255
2021-04-30,0.014839,0.020293,-0.019986,-0.001131,0.040848,0.049885,-0.007515,-0.010507,-0.008003,0.000708,0.000705,0.001453,-0.000649
2021-05-31,0.033565,0.038195,0.002734,0.044316,0.032582,0.048829,0.005114,0.009870,0.006059,0.010157,0.017477,0.075171,0.000970
2021-06-30,0.014858,0.011310,0.038808,-0.000651,0.022525,0.026639,0.001330,0.009274,0.004492,0.002682,0.008917,0.034986,0.000911

In [31]:
list_index_data = ['msci_world', 'msci_emerging', 'bb_world_agg', 'bb_corp_hy', 'us_short_treasury']

df = data[list_index_data]
df

,msci_world,msci_emerging,bb_world_agg,bb_corp_hy,us_short_treasury
1992-01-31,0.000000,0.000000,-0.002171,0.035225,-0.000984
1992-02-29,-0.020678,0.103012,-0.013095,0.024673,0.003087
1992-03-31,-0.017357,0.054748,0.003074,0.012399,-0.000196
1992-04-30,-0.066034,0.029763,0.003851,0.003798,0.009191
1992-05-31,0.027579,-0.009451,0.006528,0.014110,0.009302
...,...,...,...,...,...
2021-02-28,0.002914,0.053679,-0.006128,0.004106,0.000204
2021-03-31,0.031810,0.001014,-0.016604,0.005491,-0.000255
2021-04-30,0.020293,-0.019986,-0.007515,0.000708,-0.000649
2021-05-31,0.038195,0.002734,0.005114,0.010157,0.000970
2021-06-30,0.011310,0.038808,0.001330,0.002682,0.000911

In [37]:
world_index = index_cum_data_loading(start_date, end_date, rebal_period)
world_index = world_index[['msci_world']]
world_index.columns = ['msci_world_cum']

market_data = df.join(world_index, how='left')
market_data

/Users/raymondli/Desktop/Machine Learning/Machine learning project

,msci_world,msci_emerging,bb_world_agg,bb_corp_hy,us_short_treasury,msci_world_cum
1992-01-31,0.000000,0.000000,-0.002171,0.035225,-0.000984,1.000000
1992-02-29,-0.020678,0.103012,-0.013095,0.024673,0.003087,0.979322
1992-03-31,-0.017357,0.054748,0.003074,0.012399,-0.000196,0.962324
1992-04-30,-0.066034,0.029763,0.003851,0.003798,0.009191,0.898778
1992-05-31,0.027579,-0.009451,0.006528,0.014110,0.009302,0.923565
...,...,...,...,...,...,...
2021-02-28,0.002914,0.053679,-0.006128,0.004106,0.000204,5.039375
2021-03-31,0.031810,0.001014,-0.016604,0.005491,-0.000255,5.199679
2021-04-30,0.020293,-0.019986,-0.007515,0.000708,-0.000649,5.305197
2021-05-31,0.038195,0.002734,0.005114,0.010157,0.000970,5.507827
2021-06-30,0.011310,0.038808,0.001330,0.002682,0.000911,5.570121

In [38]:
target = 'msci_world_cum'
list_index_data = ['msci_emerging', 'bb_corp_hy', 'us_short_treasury']

select = market_data
ft_cols = list_index_data + [target]
X = select[ft_cols].values
select[ft_cols]

            msci_emerging  bb_corp_hy  us_short_treasury  msci_world_cum
1992-01-31       0.000000    0.035225          -0.000984        1.000000
1992-02-29       0.103012    0.024673           0.003087        0.979322
1992-03-31       0.054748    0.012399          -0.000196        0.962324
1992-04-30       0.029763    0.003798           0.009191        0.898778
1992-05-31      -0.009451    0.014110           0.009302        0.923565
...                   ...         ...                ...             ...
2021-02-28       0.053679    0.004106           0.000204        5.039375
2021-03-31       0.001014    0.005491          -0.000255        5.199679
2021-04-30      -0.019986    0.000708          -0.000649        5.305197
2021-05-31       0.002734    0.010157           0.000970        5.507827
2021-06-30       0.038808    0.002682           0.000911        5.570121

[354 rows x 4 columns]

In [41]:
result_df = select[ft_cols]
df_corr = result_df.corr()
df_corr

,msci_emerging,bb_corp_hy,us_short_treasury,msci_world_cum
msci_emerging,1.000000,0.618187,-0.135108,0.029420
bb_corp_hy,0.618187,1.000000,0.082979,-0.043496
us_short_treasury,-0.135108,0.082979,1.000000,-0.251427
msci_world_cum,0.029420,-0.043496,-0.251427,1.000000

In [ ]:
# Notice that the example using GMM has a low correlation between msci_world_cum and the labels, which is awkward 
# Find that the GMM assume the order of time doesn't matter
# So it is not a good model for using in stock market